config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#top"
  get "/homes/about" => 'homes#about', as: 'about'

  # 一般ユーザー用
  # URL /general_users/sign_in ...
  # コントローラーがどこに存在するか記述
  devise_for :general_users, skip: [:passwords], controllers: {
    registrations: "general_user/registrations",
    sessions: "general_user/sessions"
  }

  #ゲストログイン用
  devise_scope :general_user do
    post 'general_user/guest_sign_in', to: 'general_user/sessions#guest_sign_in'
  end

  # 自治体職員用
  # URL /staff/sign_in...
  devise_for :staffs, skip: [:registrations, :passwords], controllers: {
    sessions: "staff/sessions"
  }

  #会員側のルーティング設定
  scope module: :general_user do
    #退会確認画面
    get '/confirm' => 'general_users#confirm', as: 'confirm'
    #論理削除用のルーティング
    patch '/unsubscribe' => 'general_users#unsubscribe', as: 'unsubscribe'
    resources :posts, only: [:new, :create, :index, :edit, :show, :update, :destroy] do
      resource :dangers, only: [:create, :destroy] # 1つの投稿に1dangerしかできないため、単数形のresource
      resources :posted_comments, only: [:create, :destroy]
    end
    resources :general_users, only: [:show, :edit, :update]
    #地図機能
    #get 'maps/index'
    #resources :maps, only: [:index]

    #お問い合わせフォーム
    resources :inquiries, only: [:new, :create]
    post 'inquiries/confirm' => 'inquiries#confirm'
    post 'inquiries/back', to: 'inquiries#back', as: 'back'
    get 'done', to: 'inquiries#done', as: 'done'
  end
  #管理者側のルーティング設定
  namespace :staff do
    resources :general_users, only: [:index, :show, :edit, :update]
    resources :districts, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :posted_comments, only: [:destroy]
    end
    resources :posted_comments, only: [:index]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/district.rb
# frozen_string_literal: true

class District < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :district_name, presence: true
end

app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/staff/confirmations_controller.rb
# frozen_string_literal: true

class Staff::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_staff!, except: [:top, :about]
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staff/districts_controller.rb
class Staff::DistrictsController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @district = District.new
    @districts = District.all.page(params[:page])
  end

  def create
    @districts = District.all.page(params[:page])
    @district = District.new(district_params)
    if @district.save
      redirect_to request.referer #遷移元のページにリダイレクト
    else
      render :index
    end
  end

  def edit
    @district = District.find(params[:id])
  end

  def update
    @district = District.find(params[:id])
    if @district.update(district_params)
      redirect_to staff_districts_path
    else
      render :edit
    end
  end

  private

  def district_params
    params.require(:district).permit(:district_name)
  end
end

app/controllers/staff/general_users_controller.rb
class Staff::GeneralUsersController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @general_users = GeneralUser.all.page(params[:page])
  end

  def show
    @general_user = GeneralUser.find(params[:id])
    @posts = @general_user.posts.order(created_at: :desc).page(params[:page])
  end

  def edit
    @general_user = GeneralUser.find(params[:id])
  end

  def update
    @general_user = GeneralUser.find(params[:id])
    if @general_user.update(general_user_params)
      redirect_to staff_general_user_path(params[:id]) # 編集した会員の詳細ページにリダイレクト
    else
      render :edit
    end
  end

  private
  def general_user_params
    params.require(:general_user).permit(:profile_image, :last_name, :first_name, :kana_last_name, :kana_first_name, :email, :is_deleted)
  end

end

app/controllers/staff/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staff::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_staff!, except: [:top, :about]
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staff/passwords_controller.rb
# frozen_string_literal: true

class Staff::PasswordsController < Devise::PasswordsController
  before_action :authenticate_staff!, except: [:top, :about]
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staff/posted_comments_controller.rb
class Staff::PostedCommentsController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @posted_comments = PostedComment.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    PostedComment.find(params[:id]).destroy
    redirect_to staff_post_path(params[:post_id])
  end

end

app/controllers/staff/posts_controller.rb
class Staff::PostsController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @posted_comments = @post.posted_comments.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to staff_posts_path #staffの投稿一覧ページに遷移
  end
end

app/controllers/staff/registrations_controller.rb
# frozen_string_literal: true

class Staff::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_staff!, except: [:top, :about]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staff/sessions_controller.rb
# frozen_string_literal: true

class Staff::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    about_path  #ログインしたらアバウトページに遷移
  end

  def after_sign_out_path_for(resource)
    new_staff_session_path #ログアウトしたらログインページに遷移
  end

end

app/controllers/staff/unlocks_controller.rb
# frozen_string_literal: true

class Staff::UnlocksController < Devise::UnlocksController
  before_action :authenticate_staff!, except: [:top, :about]
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/staff/districts_helper.rb
module Staff::DistrictsHelper
end

app/helpers/staff/general_users_helper.rb
module Staff::GeneralUsersHelper
end

app/helpers/staff/posted_comments_helper.rb
module Staff::PostedCommentsHelper
end

app/helpers/staff/posts_helper.rb
module Staff::PostsHelper
end

app/views/staff/districts/edit.html.erb
<div class="container mt-5 p-5 card shadow-lg">
  <div class="row">
    <h2 class="col-5 offset-1">
      地区の編集
    </h2>
  </div>
  <div class="row">
    <div class="col-6 text-danger">
      <% if @district.errors.any? %>
        <%= @district.errors.count %>件のエラーが発生しました。
        <ul>
          <% @district.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
    <%= form_with model: @district, url: staff_district_path(@district.id), method: :patch do |f| %>
    <div class="row mt-3">
      <div class="col-3 text-right">
        <h5>地区名</h5>
      </div>
      <div class="col-5">
        <%= f.text_field :district_name,class:"form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-5 offset-3">
        <%= f.submit "変更を保存", class:"btn btn-warning" %>
      </div>
    </div>
    <% end %>
</div>

app/views/staff/districts/index.html.erb
<div class="container mt-5 p-5 card shadow-lg">
  <div class="row m-3">
    <h2 class="col-5 offset-1">
      地区一覧・新規登録
    </h2>
  </div>
  <div class="row">
    <div class="col-6 text-danger">
      <% if @district.errors.any? %>
        <%= @district.errors.count %>件のエラーが発生しました。
        <ul>
          <% @district.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="row m-3">
    <div class="col-6">
      <div class="row">
        <h4 class="col-11 offset-1">新規地区名</h4>
      </div>
      <%= form_with model: @district, url: staff_districts_path, method: :post do |f| %>
      <div class="row">
        <div class="col-8">
          <%= f.text_field :district_name,class:"form-control" %>
        </div>
        <div class="col-4">
          <%= f.submit "新規登録", class:"btn btn-success" %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="row justify-content-center">
        <div class="col-12">
          <h4 class="text-center">地区一覧</h4>
        </div>
        <table class="table table-hover text-center">
          <thead>
            <tr>
              <th scope="col">地区名</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <% @districts.each do |district| %>
            <tr>
              <td><%= district.district_name %></td>
              <td><%= link_to "編集", edit_staff_district_path(district.id), class: "btn btn-sm btn-warning" %></td>
            </tr>
          <% end %>
        </table>
        <div class="row">
          <div class="col-12">
            <%= paginate @districts %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>