config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#top"
  get "/homes/about" => 'homes#about', as: 'about'

  # 一般ユーザー用
  # URL /general_users/sign_in ...
  # コントローラーがどこに存在するか記述
  devise_for :general_users, skip: [:passwords], controllers: {
    registrations: "general_user/registrations",
    sessions: "general_user/sessions"
  }

  #ゲストログイン用
  devise_scope :general_user do
    post 'general_user/guest_sign_in', to: 'general_user/sessions#guest_sign_in'
  end

  # 自治体職員用
  # URL /staff/sign_in...
  devise_for :staffs, skip: [:registrations, :passwords], controllers: {
    sessions: "staff/sessions"
  }

  #会員側のルーティング設定
  scope module: :general_user do
    #退会確認画面
    get '/confirm' => 'general_users#confirm', as: 'confirm'
    #論理削除用のルーティング
    patch '/unsubscribe' => 'general_users#unsubscribe', as: 'unsubscribe'
    resources :posts, only: [:new, :create, :index, :edit, :show, :update, :destroy] do
      resource :dangers, only: [:create, :destroy] # 1つの投稿に1dangerしかできないため、単数形のresource
      resources :posted_comments, only: [:create, :destroy]
    end
    resources :general_users, only: [:show, :edit, :update]
    #地図機能
    #get 'maps/index'
    #resources :maps, only: [:index]

    #お問い合わせフォーム
    resources :inquiries, only: [:new, :create]
    post 'inquiries/confirm' => 'inquiries#confirm'
    post 'inquiries/back', to: 'inquiries#back', as: 'back'
    get 'done', to: 'inquiries#done', as: 'done'
  end
  #管理者側のルーティング設定
  namespace :staff do
    resources :general_users, only: [:index, :show, :edit, :update]
    resources :districts, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :posted_comments, only: [:destroy]
    end
    resources :posted_comments, only: [:index]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/general_user/confirmations_controller.rb
# frozen_string_literal: true

class GeneralUser::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_general_user!, except: [:top, :about]
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/general_user/dangers_controller.rb
# frozen_string_literal: true

class GeneralUser::DangersController < ApplicationController
  before_action :authenticate_general_user!, except: [:top, :about]
  def create
    @post = Post.find(params[:post_id])
    danger = current_general_user.dangers.new(post_id: @post.id)
    danger.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    danger = current_general_user.dangers.find_by(post_id: @post.id)
    danger.destroy
  end
end

app/controllers/general_user/general_users_controller.rb
# frozen_string_literal: true

class GeneralUser::GeneralUsersController < ApplicationController
  before_action :authenticate_general_user!, except: [:top, :about]
  before_action :ensure_guest_user, only: [:edit]
  def show
    is_matching_login_general_user
    @general_user = GeneralUser.find(params[:id])
    @posts = @general_user.posts.order(created_at: :desc).page(params[:page])
    # アソシエーションを持っているモデル同士の記述方法。特定の@general_userに関連付けられた投稿すべて(.posts)
    #orderメソッドで投稿データの日付の順序変更（desc:降順）
  end

  def edit
    is_matching_login_general_user
    @general_user = GeneralUser.find(params[:id])
  end

  def update
    is_matching_login_general_user
    @general_user = GeneralUser.find(params[:id])
    if @general_user.update(general_user_params)
      redirect_to general_user_path(current_general_user) # 一般ユーザーマイページ（詳細ページ）にリダイレクト
    else
      render :edit
    end
  end

  def unsubscribe
    @general_user = current_general_user
    #is_deletedカラムをtrueに変更することにより削除フラグを立てる
    if @general_user.last_name == "ゲスト"
      redirect_to general_user_path(current_general_user), notice: "ゲストユーザーは退会できません。"
    else
      @general_user.update(is_deleted: true)
      reset_session
      flash[:notice] = "退会処理を実行しました。"
      redirect_to root_path
    end
  end

  private
    def general_user_params
      params.require(:general_user).permit(:profile_image, :last_name, :first_name, :kana_last_name, :kana_first_name, :email, :is_deleted)
    end

    def ensure_guest_user
      @general_user = GeneralUser.find(params[:id])
      if @general_user.last_name == "ゲスト"
        redirect_to general_user_path(current_general_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end

    #URLのユーザーとログインユーザーが一致しなければ、aboutページにリダイレクト
    def is_matching_login_general_user
      general_user = GeneralUser.find(params[:id])
      unless general_user.id == current_general_user.id
        redirect_to about_path
      end
    end
end

app/controllers/general_user/inquiries_controller.rb
class GeneralUser::InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  #お問い合わせ確認画面
  #def confirm
    #@inquiry = Inquiry.new(inquiry_params)
    #入力内容が無効の場合
    #if @inquiry.invalid?
      #render :new
    #end
  #end

  #backアクションにより入力内容に誤りがあった場合は、入力内容を保持したまま前のページに戻る
  def back
    @inquiry = Inquiry.new(inquiry_params)
    render :new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  #送信完了画面
  def done
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :subject, :message)
  end
end

app/controllers/general_user/maps_controller.rb
class GeneralUser::MapsController < ApplicationController
  def index
  end
end

app/controllers/general_user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class GeneralUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_general_user!, except: [:top, :about]
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/general_user/passwords_controller.rb
# frozen_string_literal: true

class GeneralUser::PasswordsController < Devise::PasswordsController
  before_action :authenticate_general_user!, except: [:top, :about]
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/general_user/posted_comments_controller.rb
# frozen_string_literal: true

class GeneralUser::PostedCommentsController < ApplicationController
  before_action :authenticate_general_user!, except: [:top, :about]
  def create
    @post = Post.find(params[:post_id])
    @posted_comments = @post.posted_comments.order(created_at: :desc).page(params[:page])
    @posted_comment = current_general_user.posted_comments.new(posted_comment_params)
    @posted_comment.post_id = @post.id
    if @posted_comment.save
      flash.now[:notice] = "コメントを投稿しました。"
    else
      #flash.now[:alert] = "コメントに失敗しました。"
      render "general_user/posts/show"
    end
  end

  def destroy
    flash.now[:alert] = "コメントを削除しました。"
    @post = Post.find(params[:post_id])
    @posted_comments = @post.posted_comments.order(created_at: :desc).page(params[:page])
    unless PostedComment.find(params[:id]).destroy
      @posted_comment = current_general_user.posted_comments.new
      render "general_user/posts/show"
    end
  end

  private
    def posted_comment_params
      params.require(:posted_comment).permit(:posted_comment)
    end
end

app/controllers/general_user/posts_controller.rb
# frozen_string_literal: true

class GeneralUser::PostsController < ApplicationController
  before_action :authenticate_general_user!, except: [:top, :about]
  before_action :ensure_general_user, only: [:edit, :update, :destroy]

  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @post = Post.new
    #byebug
    @districts = District.all
  end

  def create
    @post = Post.new(post_params)  # フォームに入力されたデータが@postに格納される
    @post.general_user_id = current_general_user.id   # この投稿のgeneral_user_idとして、current_user.idの値を代入
    @districts = District.all
    #@post.district_id = 1 # とりあえず仮で地域を入れておく
    if @post.save  # データをデータベースに保存するためのsaveメソッド実行
      redirect_to post_path(@post.id) # 投稿した投稿の詳細画面へリダイレクト
    else
      render :new
    end
  end

  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
    @posts = @posts.where(district_id: params[:district_ids]) if params[:district_ids] && params[:district_ids].compact_blank.any?
    @posts = @posts.where('posted_title like ?', "%#{params[:keyword]}%").or(@posts.where('posted_text like ?', "%#{params[:keyword]}%")) if params[:keyword].present?
    @districts = District.all
  end

  def edit
    #@post = Post.find(params[:id])
    @districts = District.all
  end

  def show
    @post = Post.find(params[:id])
    @posted_comment = PostedComment.new
    @posted_comments = @post.posted_comments.order(created_at: :desc).page(params[:page])
  end

  def update
    #@post = Post.find(params[:id])
    @districts = District.all
    if @post.update(post_params)
      redirect_to post_path(@post.id) # 投稿詳細ページにリダイレクト
    else
      render :edit
    end
  end

  def destroy
    #post = Post.find(params[:id]) # 削除するデータ（レコード）を1件取得
    @post.destroy # データ（レコード）を削除
    redirect_to posts_path # 一覧ページにリダイレクト 要確認
  end

  private
    #ストロングパラメータ
    def post_params
      params.require(:post).permit(:posted_title, :posted_text, :posted_image, :district_id, :lat, :lng)
    end

    #URLのIDの投稿をしたユーザーとログインユーザーが一致しなければ、aboutページにリダイレクト
    def ensure_general_user
      @posts = current_general_user.posts
      @post = @posts.find_by(id: params[:id])
      redirect_to about_path if @post.blank? #もし今ログインしているユーザーの@postが空だったらaboutページへリダイレクト
    end
end

app/controllers/general_user/registrations_controller.rb
# frozen_string_literal: true

class GeneralUser::RegistrationsController < Devise::RegistrationsController
  # devise利用の機能（ユーザ登録、ログイン認証など）が
  # 使われる前にconfigure_permitted_parametersが実行される
  # before_action :configure_permitted_parameters, if: :devise_controller?
  # 4～6の記述は不要。もうdevise_controllerの機能を使っているから。

  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name])
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :kana_last_name, :kana_first_name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource) # 新規登録したらaboutページに遷移
    about_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # protected   特に不要
end

app/controllers/general_user/sessions_controller.rb
# frozen_string_literal: true

class GeneralUser::SessionsController < Devise::SessionsController
   #before_action :configure_sign_in_params, only: [:create]
  #before_action :general_user_state, only: [:create]
  before_action :reject_general_user, only: [:create]
  # GET /resource/sign_in

  def after_sign_in_path_for(resource) 
    about_path  # ログインしたらアバウトページに遷移
  end
  
  def after_sign_out_path_for(resource)
    root_path # ログアウトしたらTOPページに遷移
  end

  #ゲストログイン機能
  def guest_sign_in
    general_user = GeneralUser.guest
    sign_in general_user
    redirect_to about_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  protected
  #会員の論理削除のための記述。退会後は同じアカウントでは利用できない。
  def reject_general_user
    #emailアドレスで会員を特定
    @general_user = GeneralUser.find_by(email: params[:general_user][:email])
    #パスワードが正しいか確認し、かつis_deletedがtrue⇒退会状態、なのか確認
    if is_deleted_general_user?
      flash[:notice] = "退会済です。再度会員登録をしてご利用ください。"
      redirect_to  new_general_user_registration_path #新規会員登録画面に遷移
    else
      flash[:notice] = "項目を入力してください。"
    end
  end
  
  private
  
  def is_deleted_general_user?
    @general_user.present? && @general_user.valid_password?(params[:general_user][:password]) && (@general_user.is_deleted == true)
  end

  #protected
    # 退会しているかを判断するメソッド
    #def general_user_state
      ## 【処理内容1】 入力されたemailからアカウントを1件取得
      #@general_user = GeneralUser.find_by(email: params[:general_user][:email])
      ## アカウントを取得できなかった場合、このメソッドを終了する
      #return if !@general_user
      ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
      #if @general_user.valid_password?(params[:general_user][:password])
      ## 【処理内容3】is_deletedがfalseではなかったら、新規登録画面に遷移
        # 会員ステータスを#0:登録中、1：利用停止中、2：退会に分けたいときはこちら
        ## 【処理内容3】登録ステータスがregisteringではなかったら、新規登録画面に遷移
        #if @general_user.registration_status != "registering"
          #redirect_to new_general_user_registration_path
        #end



  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/general_user/unlocks_controller.rb
# frozen_string_literal: true

class GeneralUser::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staff/general_users_controller.rb
class Staff::GeneralUsersController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @general_users = GeneralUser.all.page(params[:page])
  end

  def show
    @general_user = GeneralUser.find(params[:id])
    @posts = @general_user.posts.order(created_at: :desc).page(params[:page])
  end

  def edit
    @general_user = GeneralUser.find(params[:id])
  end

  def update
    @general_user = GeneralUser.find(params[:id])
    if @general_user.update(general_user_params)
      redirect_to staff_general_user_path(params[:id]) # 編集した会員の詳細ページにリダイレクト
    else
      render :edit
    end
  end

  private
  def general_user_params
    params.require(:general_user).permit(:profile_image, :last_name, :first_name, :kana_last_name, :kana_first_name, :email, :is_deleted)
  end

end

app/helpers/general_user/dangers_helper.rb
# frozen_string_literal: true

module GeneralUser::DangersHelper
end

app/helpers/general_user/general_users_helper.rb
# frozen_string_literal: true

module GeneralUser::GeneralUsersHelper
end

app/helpers/general_user/inquiries_helper.rb
module GeneralUser::InquiriesHelper
end

app/helpers/general_user/maps_helper.rb
module GeneralUser::MapsHelper
end

app/helpers/general_user/posted_comments_helper.rb
# frozen_string_literal: true

module GeneralUser::PostedCommentsHelper
end

app/helpers/general_user/posts_helper.rb
# frozen_string_literal: true

module GeneralUser::PostsHelper
end

app/views/general_user/general_users/confirm.html.erb
<div class="container mt-5">
  <div class="row pt-5">
    <div class="col-12 text-center">
      <h1>退会しますか？</h1>
    </div>
  </div>
  <div class="row mt-3">
    <h4 class="col-12 text-center">
      退会手続きをされますと、画像やコメントの投稿がご利用いただけなくなります。<br>
      再度ご利用いただく際は、新規登録が必要になります。<br>
      本当に退会してよろしいですか？
    </h4>
  </div>
  <div class="row mt-5">
    <div class="col-4 offset-2 text-center">
      <%= link_to "はい、退会します", unsubscribe_path, method: :patch, "data-confirm" => "本当に退会しますか？", class:"btn btn-danger btn-lg" %>
    </div>
    <div class="col-4 text-center">
      <%= link_to "いいえ、退会しません", general_user_path(current_general_user), class:"btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/general_user/general_users/edit.html.erb
<div class="container mt-5 p-5 card shadow-lg">
  <div class="row m-3">
    <h1 class="col-5 offset-1">
      プロフィール編集
    </h1>
  </div>
  <div class="row">
    <div class="col-6 text-danger">
      <% if @general_user.errors.any? %>
        <%= @general_user.errors.count %>件のエラーが発生しました。
        <ul>
          <% @general_user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <%= form_with model: @general_user do |f| %>
    <div class="row mt-3">
      <div class="col-3 offset-1 text-right">
        <h5>プロフィール画像</h5>
      </div>
      <div class="col-6">
        <%= f.file_field :profile_image, placeholder:"プロフィール画像", accept: "image/*" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-2 offset-1 text-right">
        <h5>名前</h5>
      </div>
      <div class="col-1 text-right">
        <h6>姓</h6>
      </div>
      <div class="col-3">
        <%= f.text_field :last_name, autofocus: true,class:"form-control" %>
      </div>
      <div class="col-1 text-right">
        <h6>名</h6>
      </div>
      <div class="col-3">
        <%= f.text_field :first_name, autofocus: true,class:"form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-1 offset-3 text-right">
        <h6>セイ</h6>
      </div>
      <div class="col-3">
        <%= f.text_field :kana_last_name, autofocus: true,class:"form-control" %>
      </div>
      <div class="col-1 text-right">
        <h6>メイ</h6>
      </div>
      <div class="col-3">
        <%= f.text_field :kana_first_name, autofocus: true,class:"form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-3 offset-1 text-right">
        <h5>メールアドレス</h5>
      </div>
      <div class="col-5">
        <%= f.email_field :email, autofocus: true, autocomplete: "email",class:"form-control" %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-3 offset-4">
        <%= f.submit "変更を保存", class:"btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/general_user/general_users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-3 p-3 card">
<!--一般ユーザーの詳細-->
      <h4 class="row justify-content-center m-3">
        プロフィール
      </h4>
      <%= image_tag @general_user.get_profile_image(300,300) %>
      <div class="row m-3 justify-content-center mt-2">
        <h6 class="d-flex flex-column">氏名:<%= @general_user.last_name %><%= @general_user.first_name %></h6>
        <h6 class="d-flex flex-column mt-2">カナ:<%= @general_user.kana_last_name %><%= @general_user.kana_first_name %></h6>
        <h6 class="d-flex flex-column mt-2">Email:<%= @general_user.email %></h6>
      <!--ログインしているユーザー本人のみ編集リンクを表示させる-->
      <%# if @general_user == current_general_user %>
        <div class="d-flex flex-column mt-3"><%= link_to "プロフィールを編集", edit_general_user_path(@general_user.id), class: "btn btn-warning" %></div>
        <div class="d-flex flex-column mt-3"><%= link_to "退会する", confirm_path, class: "btn btn-danger" %></div>
      <%# end %>
      </div>
    </div>
    <div class="col-9 pl-5">
      <!--一般ユーザーの投稿一覧-->
      <h3><%= @general_user.last_name %><%= @general_user.first_name %>さんの投稿一覧</h3>
      <table class="table table-hover mt-3 text-center">
        <thead>
          <tr>
            <th scope="col">投稿日時</th>
            <th scope="col">地区</th>
            <th scope="col">タイトル</th>
            <th scope="col">画像</th>
            <th scope="col">コメント数</th>
            <th scope="col">危険マーク数</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td><%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
            <td><%= post.district.district_name %></td>
            <td><%= post.posted_title %></td>
            <td><%= image_tag post.get_image(100,100) %></td>
            <td><%= post.posted_comments.count %>件</td>
            <td><i class="fas fa-exclamation-triangle text-danger"></i><%= post.dangers.count %></td>
            <td><%= link_to "詳細", post_path(post.id), class: "btn btn-info" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="col-2 text-center">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>