config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#top"
  get "/homes/about" => 'homes#about', as: 'about'

  # 一般ユーザー用
  # URL /general_users/sign_in ...
  # コントローラーがどこに存在するか記述
  devise_for :general_users, skip: [:passwords], controllers: {
    registrations: "general_user/registrations",
    sessions: "general_user/sessions"
  }

  #ゲストログイン用
  devise_scope :general_user do
    post 'general_user/guest_sign_in', to: 'general_user/sessions#guest_sign_in'
  end

  # 自治体職員用
  # URL /staff/sign_in...
  devise_for :staffs, skip: [:registrations, :passwords], controllers: {
    sessions: "staff/sessions"
  }

  #会員側のルーティング設定
  scope module: :general_user do
    #退会確認画面
    get '/confirm' => 'general_users#confirm', as: 'confirm'
    #論理削除用のルーティング
    patch '/unsubscribe' => 'general_users#unsubscribe', as: 'unsubscribe'
    resources :posts, only: [:new, :create, :index, :edit, :show, :update, :destroy] do
      resource :dangers, only: [:create, :destroy] # 1つの投稿に1dangerしかできないため、単数形のresource
      resources :posted_comments, only: [:create, :destroy]
    end
    resources :general_users, only: [:show, :edit, :update]
    #地図機能
    #get 'maps/index'
    #resources :maps, only: [:index]

    #お問い合わせフォーム
    resources :inquiries, only: [:new, :create]
    post 'inquiries/confirm' => 'inquiries#confirm'
    post 'inquiries/back', to: 'inquiries#back', as: 'back'
    get 'done', to: 'inquiries#done', as: 'done'
  end
  #管理者側のルーティング設定
  namespace :staff do
    resources :general_users, only: [:index, :show, :edit, :update]
    resources :districts, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :posted_comments, only: [:destroy]
    end
    resources :posted_comments, only: [:index]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/danger.rb
# frozen_string_literal: true

class Danger < ApplicationRecord
  belongs_to :general_user
  belongs_to :post
end

app/models/district.rb
# frozen_string_literal: true

class District < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :district_name, presence: true
end

app/models/general_user.rb
# frozen_string_literal: true

class GeneralUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :posted_comments, dependent: :destroy
  has_many :dangers, dependent: :destroy
  has_one_attached :profile_image

  #会員ステータスを3つに分けたいときは以下を使う
  #enum registration_status: { registering: 0, in_suspend: 1, unsubscribe: 2 }
                                #0:登録中、1：利用停止中、2：退会
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def get_profile_image(width, height) # viewでサイズを指定しているので、(width,height)を入れないとArgumentErrorになる
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed # メソッドに対し引数を設定し、引数に設定した値に画像サイズを変換するようにした
  end

  #退会済みのユーザーが同じアカウントでログインできないように制約を設けている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@user') do |general_user|
      general_user.password = SecureRandom.urlsafe_base64
      #パスワードを特定されないように、ランダム文字列にしている
      general_user.last_name = "ゲスト"
      general_user.first_name = "ユーザー"
      general_user.kana_last_name = "ゲスト"
      general_user.kana_first_name = "ユーザー"
    end
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :posted_image
  belongs_to :general_user
  belongs_to :district
  has_many :posted_comments, dependent: :destroy
  has_many :dangers, dependent: :destroy

  validates :district_id, presence: true
  validates :posted_title, presence: true
  validates :posted_text, presence: true
  validates :posted_image, presence: true
  validates :lat, presence: true
  validates :lng, presence: true

  def get_image(width, height) #ここで指定したget_imageメソッドを、viewの画像のところで使う。
    unless posted_image.attached?
      file_path = Rails.root.join('app/assets/images/画像未登録.jpg') #定型文のようなもの。（）内は自分の保存したjpgを書く。
      posted_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg') #.attachの前はカラム名。以降は定型文みたいなもの。
    end
    posted_image.variant(resize_to_limit: [width, height]).processed
  end
  #引数で渡されたgeneral_user.idがdangersテーブル内に存在するか調べる
  def dangered_by?(general_user)
    dangers.exists?(general_user_id: general_user.id)
  end
end

app/models/posted_comment.rb
# frozen_string_literal: true

class PostedComment < ApplicationRecord
  belongs_to :general_user
  belongs_to :post

  validates :posted_comment, presence: true
end

app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @post = Post.new
  end

  def create
    #データを受け取り新規登録するためのインスタンス作成
    post = Post.new(post_params)
    #データをデータベースに保存するためのsaveメソッド実行
    post.save
    #トップ画面へリダイレクト 後で変更するかも
    redirect_to '/top'
  end

  def index
    @posts = Post.all
  end

  def edit
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private
  #ストロングパラメータ
  def post_params
    params.require(:post).permit(:posted_title, :posted_text)
    #後ほど地区選択もpermitの中に入れるかも
  end
end

app/controllers/staff/posts_controller.rb
class Staff::PostsController < ApplicationController
  before_action :authenticate_staff!, except: [:top, :about]
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @posted_comments = @post.posted_comments.all.order(created_at: :desc).page(params[:page])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to staff_posts_path #staffの投稿一覧ページに遷移
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/general_user/dangers_helper.rb
# frozen_string_literal: true

module GeneralUser::DangersHelper
end

app/helpers/general_user/maps_helper.rb
module GeneralUser::MapsHelper
end

app/helpers/general_user/posts_helper.rb
# frozen_string_literal: true

module GeneralUser::PostsHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/staff/districts_helper.rb
module Staff::DistrictsHelper
end

app/helpers/staff/general_users_helper.rb
module Staff::GeneralUsersHelper
end

app/helpers/staff/posts_helper.rb
module Staff::PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsunagarubousaiNet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--管理者がログイン状態の時-->
  <% if staff_signed_in? %>
  <body class="d-flex flex-column vh-100 backstaffcolor">
    <header class="shadow-sm headerstaffcolor">
     <!--それ以外の時-->
  <% else %>
  <body class="d-flex flex-column vh-100 backcolor">
    <header class="shadow-sm headercolor">
  <% end %>
      <nav class="navbar navbar-expand-lg navbar-light text-light">
        <div class="container-fluid">
          <!--ロゴ-->
          <div class="col-2">
            <a class="navbar-brand p-3 text-light" href="/"><%= "つながる防災.net" %></a>
          </div>
          <!--ようこそ-->
          <div class="col-3 text-center">
            <% if general_user_signed_in? %>
              <h10 class="text-light">ようこそ、<%= current_general_user.last_name %><%= current_general_user.first_name %>さん！</h10>
            <% end %>
          </div>
          <!--ヘッダーの内容-->
            <!--ハンバーガーメニュー-->
          <div class="col-7">
            <button class="navbar-toggler text-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon text-light"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <!--管理者がログイン状態の時-->
                <% if staff_signed_in? %>
                <il class="nav-item">
                  <%= link_to "お知らせ", about_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "投稿一覧", staff_posts_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "コメント一覧", staff_posted_comments_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "会員一覧", staff_general_users_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "地区一覧", staff_districts_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "ログアウト", destroy_staff_session_path, method: :delete, class: 'nav-link text-light' %>
                </il>
                <!--一般ユーザーがログイン状態の時-->
                <% elsif general_user_signed_in? %>
                <il class="nav-item">
                  <%= link_to "お知らせ", about_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "危険箇所の投稿", new_post_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "投稿一覧", posts_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "マイページ", general_user_path(current_general_user.id), class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "ログアウト", destroy_general_user_session_path, method: :delete, class: 'nav-link text-light' %>
                </il>
                <!--ログアウト状態の時-->
                <% else %>
                <il class="nav-item">
                  <%= link_to "お知らせ", about_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "新規会員登録", new_general_user_registration_path, class: 'nav-link text-light' %>
                </il>
                <il class="nav-item">
                  <%= link_to "ログイン", new_general_user_session_path, class: 'nav-link text-light' %>
                </il>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    </header>
    <main class="mb-auto">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </main>
    <!--管理者がログイン状態の時-->
    <% if staff_signed_in? %>
    <footer class="text-white pt-5 pb-4 headerstaffcolor">
    <!--それ以外の時-->
    <% else %>
    <footer class="text-white pt-5 pb-4 headercolor">
    <% end %>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <%= link_to "お問い合わせ", new_inquiry_path, class: 'text-light' %>
        </div>
      </div>
    </div>
    </footer>
    </footer>
  </body>
  </body>
</html>